# Dependencies must also be added to LicensesDialog.java

[versions]
morphe-patcher = "1.10.0"
# Tracking https://github.com/google/smali/issues/100.
smali = "d92701d947"
agp = "9.1.0"
gson = "2.14.0"
kotlin = "2.4.10"
annotation = "1.10.0"

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
morphe-patcher = { module = "app.morphe:morphe-patcher", version.ref = "morphe-patcher" }
smali = { module = "com.github.MorpheApp.smali:smali", version.ref = "smali" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
